# Function that randomly picks a question from the data frame generated by
# quiz_generator()
question_picker <- function(questions, current_attempt, correct_questions, game_over) {
  shiny::reactive({
    if (game_over()) {
      return(NULL)
    }
    
    # If current attempt changes, reevaluate the question_picker
    current_attempt()
    
    # Filter the data frame to include only rows where correct is FALSE
    correct <- correct_questions()
    
    if (length(correct) > 0) {
      incorrect_questions <- questions()[-correct, ]
    } else {
      incorrect_questions <- questions()
    }
    
    # Check if there are any incorrect questions
    if (nrow(incorrect_questions) > 0) {
      # Pick a random row from the filtered data frame
      random_index <- sample(nrow(incorrect_questions), 1)
      random_question <- incorrect_questions[random_index, ]
    } else {
      random_question <- NULL
    }  
    
    random_question
  })
}
